server:
  port: 9201
spring:
  cloud:
    gateway:
      routes:
        - id: retry_route
          uri: http://localhost:8201
          predicates:
            - Method=GET
          filters:
            - name: Retry
              retries: 1 #需要进行重试的次数
              statuses: BAD_GATEWAY #返回哪个状态码需要重试，返回状态码为5XX进行重试
              backoff:
                firstBackOff: 10ms
                maxBackoff: 50ms
                factor: 2
                basedOnPreviousValue: false