server:
  port: 9301
spring:
  application:
    name: admin-security-server
  security:
    user:
      name: macro
      password: 123456
  boot: #不显示spring-security-server的监控信息
    admin:
      discovery:
        ignored-services: ${spring.application.name}
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8001/eureka/